name = "cfp-specialprize-club"
main = "src/index.js"
compatibility_date = "2024-02-27"

# Site configuration for static assets
[site]
bucket = "./"

# D1 Database configuration
[[d1_databases]]
binding = "securus_d1_binding"
database_name = "securus"
database_id = "8d4be126-5687-464b-bc74-88f21d6d64e7"

# Email configuration
send_email = [
   	{name = "email-kal", destination_address = "kal@dhinsa.com"},
]

